logging:
  level:
    org.springframework: DEBUG
    ROOT: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.security: INFO
    fr.codecake.ecom: DEBUG
    org.apache.hc.client5.http: INFO

spring:
#  autoconfigure:
#    exclude:
#    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/codecake
    username: codecake
    password: codecake
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml
    default-schema: ecommerce
    liquibase-schema: ecommerce
